/**
 * Every user-visible string, in one place, ported from the Android app's
 * `strings.xml` and `strings_design.xml`. Wording is deliberately identical
 * where the two clients do the same thing, so a user who knows one knows the
 * other — and where the desktop differs (no camera, a mouse instead of a
 * finger) the wording is adjusted rather than left misleading.
 *
 * Functions are the strings that take arguments; everything else is a constant.
 */

export const S = {
  appName: 'Remote Terminal',
  appTagline: 'Secure. Fast. Everywhere.',

  // Navigation
  navHome: 'Home',
  navMachines: 'Machines',
  navTerminals: 'Terminals',
  navSettings: 'Settings',

  // Connection states
  stateConnected: 'Connected',
  stateConnecting: 'Connecting…',
  stateReconnecting: 'Reconnecting…',
  stateReconnectingIn: (s) => `Reconnecting in ${s}s…`,
  stateDisconnected: 'Not connected',
  stateUnpaired: 'Not paired',
  stateFailed: (reason) => `Cannot connect: ${reason}`,
  retryNow: 'Retry',

  // Machines
  machineOnline: 'Online',
  machineOffline: 'Offline',
  machineLastSeen: (when) => `Last seen ${when}`,
  machineNeverSeen: 'Never connected',
  machineSessions: (n) => `${n} ${n === 1 ? 'terminal' : 'terminals'}`,
  machinesEmptyAction: 'How to install the agent',
  machinesHelp:
    'On the computer:\n\n' +
    'Windows:\n  install-windows.ps1 -Install -Server wss://relay -EnrollToken …\n\n' +
    'Ubuntu / Linux:\n  sudo ./install-linux.sh --server wss://relay --enroll-token …\n\n' +
    'The machine appears in this list once it connects to the relay.',
  machinesSubtitle: 'Manage connected computers',
  machinesSearchHint: 'Search by name, host or operating system',
  machinesAddNew: 'Add a new machine',
  refresh: 'Refresh',

  // Filters and sorting
  filterAll: 'All',
  filterOnline: 'Online',
  filterOffline: 'Offline',
  filterFilters: 'Filters',
  filterActive: 'Active',
  filterDetached: 'Detached',
  filterPinned: 'Pinned',
  sortName: 'Name',
  sortRecent: 'Recently used',
  sortStatus: 'Status',

  // Machine cards
  statTerminals: 'Terminals',
  statAgent: 'Agent',
  statLatency: 'Latency',
  statUptime: 'Uptime',
  statActiveCount: (n) => `${n} active`,
  statVersion: (v) => `v${v}`,
  statLatencyMs: (ms) => `${ms} ms`,
  valueUnknown: '—',
  presenceOnlineLastSeen: 'Online · Last seen now',
  presenceOfflineSince: (when) => `Offline · ${when}`,
  actionConnect: 'Connect',
  actionTerminals: 'Terminals',
  actionDetails: 'Details',
  actionSettings: 'Settings',
  actionUnavailable: 'Unavailable',
  actionFavourite: 'Favourite',
  actionUnfavourite: 'Remove from favourites',
  actionPin: 'Pin',
  actionUnpin: 'Unpin',
  actionContinue: 'Continue',
  actionRetry: 'Try again',
  actionDuplicate: 'Duplicate',

  // Home
  homeRecentTerminals: 'Recent terminals',
  homeViewAll: 'View all',
  homeQuickAccess: 'Quick access',
  quickRecent: 'Recent',
  quickFavourites: 'Favourites',
  homeAddMachine: 'Add machine',
  tipsTitle: 'Tips',
  tipsBody: 'Pin favourite machines and terminals for quick access.',
  learnMore: 'Learn more',
  tipsHelpTitle: 'Favourites',
  tipsHelpBody:
    'Click the star on a machine, or “Pin” in a terminal’s menu, to keep it at the top of Home and in the Pinned filter.',

  // All terminals
  terminalsSubtitle: 'Resume and manage sessions',
  terminalsSearchHint: 'Search terminal sessions',
  terminalsEncryptedTitle: 'Sessions are encrypted',
  terminalsEncryptedBody: 'Commands and output are protected in transit.',
  terminalsInsecureTitle: 'This relay is not encrypted',
  terminalsInsecureBody: 'You paired over ws://. Commands and output travel in clear text.',
  badgeActive: 'Active',
  badgeNew: 'New',
  badgeLatest: 'Latest',
  badgeOpen: 'Open',

  // Machine screen
  tabTerminals: 'Terminals',
  tabDetails: 'Details',
  tabSettings: 'Settings',
  machineSessionsNoteTitle: (n) => `${n} terminal ${n === 1 ? 'session' : 'sessions'}`,
  machineSessionsNoteBody: 'Sessions remain available when you leave this screen.',
  agentVersionShort: (v) => `Agent ${v}`,
  agentOfflineHint: 'This machine is offline. Terminals cannot be started until it reconnects.',

  // Machine details
  machineDetailsTitle: 'Machine details',
  metricCpu: 'CPU',
  metricMemory: 'Memory',
  metricStorage: 'Storage',
  metricUptime: 'Uptime',
  systemInformation: 'System information',
  infoOperatingSystem: 'Operating system',
  infoAgentVersion: 'Agent version',
  infoConnection: 'Connection',
  infoMachineId: 'Machine ID',
  infoShells: 'Shells',
  metricsUnavailable: 'This agent does not report system metrics.',
  agentUpToDate: (v) => `${v} · Up to date`,
  connectionWithLatency: (host, ms) => `${host} · ${ms} ms`,

  // Machine settings
  machineSettingsTitle: 'Machine settings',
  fieldDisplayName: 'Display name',
  fieldRelayServer: 'Relay server',
  hintSecure: 'Secure',
  hintInsecure: 'Not encrypted',
  settingAutoReconnect: 'Auto reconnect',
  settingAutoReconnectDesc: 'Reconnect automatically after network changes',
  settingKeepAlive: 'Keep alive',
  settingKeepAliveDesc: 'Maintain sessions while the window is hidden',
  settingConnectionAlerts: 'Connection alerts',
  settingConnectionAlertsDesc: 'Notify when this machine goes offline',
  securityAgentToken: 'Agent token',
  securityAgentTokenValue: '••••••••••••••',
  securityAgentTokenNote: 'Held by the relay. Re-enrol the agent to replace it.',
  securityEncryption: 'Encryption',
  securityEncryptionTls: 'TLS · End-to-end protected',
  securityEncryptionPlain: 'ws:// · Not encrypted',
  saveChanges: 'Save changes',
  saved: 'Saved',
  renameMachine: 'Rename machine',
  removeMachine: 'Remove machine',
  removeMachineConfirm: (name) =>
    `Remove “${name}”?\n\nIts agent token is revoked immediately; the agent must be enrolled again to reconnect. Running terminals on it are closed.`,
  copyHostname: 'Copy hostname',
  copied: 'Copied',

  // Pairing
  addMachineTitle: 'Add machine',
  addMachineSubtitle: 'Pair this computer with your relay',
  stepConnection: '1 Connection',
  stepVerify: '2 Verify',
  stepFinish: '3 Finish',
  fieldPairingCode: 'Pairing code',
  hintPaste: 'Paste link',
  pairingCodeHelp: 'Find this one-time code in the Remote Terminal agent on the computer you want to reach.',
  or: 'OR',
  pastePairingLink: 'Paste a pairing link',
  pairingSecurityNote:
    'No inbound port is opened. Both sides connect outward to your relay over encrypted WebSockets.',
  needAgent: 'Need the computer agent?',
  viewSetupGuide: 'View setup guide',
  verifyTitle: 'Verifying pairing code',
  verifyBody: (host) => `Redeeming the code with ${host}. This takes a moment.`,
  verifyFailedTitle: 'Pairing did not complete',
  finishTitle: 'This device is paired',
  finishBody: (host) => `Machines that connect to ${host} now appear in your list. Nothing was opened on your network.`,
  finishAction: 'Go to machines',
  pairNameHint: 'Name of this device',
  pairRelayHint: 'wss://relay.example.com',
  pairCodeHint: '6 digits',
  pairErrorUrl: 'Enter the relay URL (wss://…)',
  pairErrorCode: 'Enter the 6-digit code',
  pairInsecureTitle: 'Unencrypted connection',
  pairInsecureText: (relay) =>
    `${relay} uses ws:// without TLS. Your device token and everything you type would travel in clear text. Use wss:// unless this is a private test network.`,
  pairInsecureContinue: 'Use anyway',
  pairFailed: (message) => `Pairing failed: ${message}`,
  pairLinkNotFound: 'The clipboard does not hold a pairing code or a remoteterminal:// link.',
  unpair: 'Unpair this device',
  unpairConfirm:
    'Unpair this device?\n\nThe device token is deleted locally. Open terminals keep running on the machines; pair again to get back to them.',
  unpairedNotice: 'This device was unpaired. Pair it again to continue.',

  // Devices
  devices: 'Paired devices',
  deviceThisOne: 'This device',
  deviceLastSeen: (when) => `Last seen ${when}`,
  deviceOnline: 'Online now',
  addDevice: 'Add device',
  addDeviceRelay: (relay) => `Relay: ${relay}`,
  revokeDevice: 'Revoke',
  revokeDeviceConfirm: (name) => `Revoke “${name}”?\n\nIt is disconnected immediately and must pair again.`,
  renameDevice: 'Rename this device',
  devicesEmpty: 'No paired devices.',
  pairingCodeTitle: 'Pairing code',
  pairingCodeBody: (minutes) =>
    `Type this on the other device, or copy the link. It expires in ${minutes} ${minutes === 1 ? 'minute' : 'minutes'}.`,
  copyLink: 'Copy link',

  // New terminal
  newTerminal: 'New terminal',
  newTerminalTitle: 'New terminal',
  newTerminalSubtitle: 'Start a persistent shell session',
  labelMachine: 'MACHINE',
  fieldTerminalName: 'Terminal name',
  fieldTerminalNameHint: 'Optional',
  fieldShell: 'Shell',
  fieldWorkingDirectory: 'Working directory',
  workingDirectoryHelp: 'Leave empty to use the account’s home directory.',
  workingDirectoryHint: '/home/you',
  recentDirectories: 'Recent',
  toggleRestore: 'Restore on reconnect',
  toggleRestoreDesc: 'Keep the terminal running when disconnected',
  toggleNotify: 'Notify when command finishes',
  toggleNotifyDesc: 'For commands that run longer than 30 seconds',
  createTerminal: 'Create terminal',
  creatingTerminal: 'Starting terminal…',
  advancedOptions: 'Advanced options',
  fieldInitialCommand: 'Command to run on start',
  fieldInitialCommandHint: 'e.g. npm run dev',
  fieldScrollback: 'Scrollback lines',
  chooseMachine: 'Choose a machine',
  noOnlineMachines: 'No machine is online right now.',
  shellDefault: 'default',

  // Terminal
  terminal: 'Terminal',
  terminalNewTab: 'New tab',
  tabClose: 'Close tab',
  tabKeepRunning: 'Keep running',
  tabKeepRunningDesc: 'Close the tab but leave the shell running on the machine. You can reopen it from the machine screen.',
  tabTerminate: 'Terminate',
  tabTerminateDesc: 'End the shell process and everything running in it.',
  tabCloseTitle: (name) => `Close “${name}”?`,
  renameTerminal: 'Rename terminal',
  search: 'Search',
  searchHint: 'Find in scrollback',
  searchNone: 'No matches',
  searchCount: (cur, total) => `${cur} of ${total}`,
  searchPrev: 'Previous match',
  searchNext: 'Next match',
  closeSearch: 'Close search',
  commandBar: 'Command bar',
  commandPlaceholder: 'Type a command…',
  shortcuts: 'Shortcuts',
  shortcutsKeys: 'Keys',
  shortcutsCommands: 'Commands',
  shortcutsCommandsHint: 'Commands run when clicked (Enter is sent). Edit them in Settings.',
  selectAll: 'Select all',
  copy: 'Copy',
  paste: 'Paste',
  pasteConfirmTitle: (n) => `Paste ${n} lines?`,
  pasteConfirmText: 'The clipboard contains several lines. Each line ends with Enter and will run as a command.',
  pasteConfirmOk: 'Paste',
  clearTerminal: 'Clear screen',
  pasteFile: 'Paste file',
  pasteImage: 'Paste image',
  attachFile: 'Attach file…',
  attachFileUnavailable: 'No file picker is available.',
  pasteFileNone: 'No file on the clipboard. Copy a file in Explorer first.',
  pasteImageNone: 'No image on the clipboard.',
  pasteFileUnsupported: 'This machine’s agent is too old to receive files.',
  pasteFileUploading: 'Uploading file…',
  pasteFileDone: (path) => `Saved to ${path}`,
  pasteFileFailed: (why) => `Could not send the file: ${why}`,
  newLines: (n) => (n === 1 ? '↓ 1 new line' : `↓ ${n} new lines`),
  jumpToBottom: 'Jump to newest output',
  send: 'Send',
  terminalOffline: 'Machine offline — waiting to reconnect',
  terminalAttaching: 'Attaching…',
  terminalExited: 'Process exited',
  terminalClosed: 'Terminal closed',
  terminalGone: 'This terminal no longer exists on the machine',
  terminalNotConnected: 'Not connected',
  terminalThemeTitle: 'Terminal theme',
  terminalThemeDefault: (name) => `Use app default (${name})`,
  terminalSettings: 'Terminal settings',
  keyboardShortcuts: 'Keyboard shortcuts',
  duplicateNoPath: 'The shell has not reported a directory, so the copy starts at home.',
  keyRowsToggle: 'Key rows',
  sessionStateRunning: 'active',
  sessionStateDetached: 'detached',
  sessionStateExited: (code) => `exited (${code})`,
  confirmDisconnectTitle: (name) => `Disconnect “${name}”?`,
  confirmDisconnectBody: 'The shell keeps running on the machine. Reopen it any time from the machine screen.',
  confirmDisconnectAction: 'Disconnect',

  // App settings
  settingsSubtitle: 'Personalise Remote Terminal',
  settingsSearchHint: 'Search settings',
  groupAppearance: 'Appearance',
  groupTerminal: 'Terminal',
  groupKeyboard: 'Keyboard',
  groupNotifications: 'Notifications',
  groupSecurityConnection: 'Security & connection',
  settingTheme: 'Theme',
  settingThemeDesc: 'App appearance',
  settingTerminalFont: 'Terminal font',
  settingTerminalFontValue: (family, size) => `${family} · ${size} px`,
  settingTerminalColours: 'Colour scheme',
  settingCursor: 'Cursor',
  settingExtraKeys: 'Extra keys row',
  settingExtraKeysDesc: 'Ctrl, Alt, arrows and common symbols',
  settingCommandNotifications: 'Command notifications',
  settingCommandNotificationsDesc: 'Notify when long commands finish',
  settingCommandHistory: 'Command history',
  settingCommandHistoryDesc: (n) => `Store the last ${n} commands locally`,
  settingWheelTabs: 'Switch terminals with the wheel',
  settingWheelTabsDesc: 'Shift + wheel over the grid moves to the next or previous tab',
  settingScrollback: 'Scrollback',
  settingKeepAwake: 'Keep the display awake',
  settingBell: 'Terminal bell',
  settingOsc52: 'Programs may set the clipboard',
  settingOsc52Desc: 'OSC 52 clipboard writes',
  settingPasteConfirm: 'Confirm multi-line paste',
  settingCommandBar: 'Command bar',
  settingCommandBarDesc: 'Show the command input under the terminal',
  settingKeyRows: 'Key rows',
  settingKeyRowsDesc: 'Edit the three extra-key rows',
  settingCommandShortcuts: 'Command shortcuts',
  settingCommandShortcutsDesc: 'Chips in the shortcuts sheet',
  settingNotifyOffline: 'Machine goes offline',
  settingNotifyExit: 'Terminal process exits',
  settingNotifyBell: 'Terminal bell',
  settingAppLock: 'App lock',
  settingAppLockDesc: 'Ask for Windows Hello before showing anything',
  settingAppLockUnavailable: 'Windows Hello is not set up on this machine',
  settingDefaultRelay: 'Default relay',
  settingPairedDevices: 'Paired devices',
  settingDeviceId: 'Device ID',
  settingUnpair: 'Unpair this device',
  settingConfigFolder: 'Settings folder',
  settingConfigFolderDesc: 'Where this device keeps its settings and sealed token',
  aboutLine: (version, protocol) => `Remote Terminal ${version} • Wire protocol v${protocol}`,
  prefKeysHelp:
    'Space-separated keys, one row per line. Names: ESC CTRL ALT SHIFT TAB ENTER BKSP UP DOWN LEFT RIGHT HOME END PGUP PGDN INS DEL F1–F12. Any other token is typed literally; write a|b for a right-click alternate.',
  prefCommandsHelp: 'One per line: label = command',

  // Terminal font screen
  terminalFontTitle: 'Terminal font',
  fontSizeLabel: 'Size',
  lineSpacingLabel: 'Line spacing',
  fontPreviewText: '$ ls -la ~/projects',
  fontBundled: 'Bundled mono',
  fontSystem: 'System monospace',
  fontFamilyLabel: 'Typeface',
  cursorBlinkLabel: 'Blinking cursor',
  previewLabel: 'Preview',

  // Presets
  presetsTitle: 'Terminal presets',
  presetsSubtitle: 'Saved ways to start a terminal',
  presetsManage: 'Manage presets',
  presetsEmptyTitle: 'No presets yet',
  presetsEmptyBody:
    'Save the machine, shell, folder and first command you keep typing, then start it in one click.',
  presetNew: 'New preset',
  presetEditTitle: 'Edit preset',
  presetSubtitle: 'Saved for one-click terminals',
  presetStart: 'Start from preset',
  presetSave: 'Save preset',
  presetSaveAs: 'Save as preset',
  presetSaved: (name) => `Saved “${name}”`,
  presetNeedsName: 'Give the preset a name first.',
  presetNameHint: 'API logs',
  presetAnyMachine: 'Any machine',
  presetAnyMachineDesc: 'Asks which machine when it starts',
  presetDefaultShell: 'The machine’s default shell',
  presetMachineGone: 'Machine not paired',
  presetNoDirectory: 'Home directory',
  presetNoMachine: 'That machine is no longer paired.',
  presetCommandHelp:
    'Typed into the new shell as its first line, right after the working directory. Leave it empty to just open a shell.',
  presetNoCommand: 'No start-up command',
  presetCommandLine: (cmd) => `❯ ${cmd}`,
  presetDeleteTitle: (name) => `Delete “${name}”?`,
  presetDeleteBody: 'The preset is removed from this device. Terminals already started from it keep running.',

  // Command history
  commandHistoryTitle: 'Command history',
  commandHistoryEmpty: 'Nothing yet. Commands you send from the command bar are listed here.',
  commandHistoryClear: 'Clear history',
  commandHistoryCleared: 'History cleared',

  // Shared states
  emptyMachinesTitle: 'No machines yet',
  emptyMachinesBody:
    'Install the agent on a computer and pair it. It appears here as soon as it reaches the relay.',
  emptyTerminalsTitle: 'No terminals yet',
  emptyTerminalsBody: 'Start one on a machine and it stays running even when you close the app.',
  emptySearchTitle: 'No matches',
  emptySearchBody: (q) => `Nothing matches “${q}”. Try a shorter search.`,
  emptyFilterTitle: 'Nothing in this filter',
  emptyFilterBody: 'Switch to another filter to see the rest.',
  offlineTitle: 'Not connected to the relay',
  offlineBody:
    'Your machines and terminals are shown from the last sync. They resume as soon as the connection returns.',
  errorTitle: 'Something went wrong',
  errorGeneric: (why) => `Something went wrong: ${why}`,
  clearSearch: 'Clear search',

  // Notifications
  notifOfflineTitle: (name) => `${name} went offline`,
  notifOfflineText: 'Terminals will resume when it reconnects.',
  notifExitTitle: (name) => `“${name}” exited`,
  notifExitText: (machine, code) => `${machine} · exit code ${code}`,
  notifBellTitle: (name) => `Bell in “${name}”`,

  // Common
  ok: 'OK',
  cancel: 'Cancel',
  save: 'Save',
  delete: 'Delete',
  remove: 'Remove',
  edit: 'Edit',
  back: 'Back',
  more: 'More',
  open: 'Open',
  timeJustNow: 'just now',
  timeMinutes: (n) => `${n}m ago`,
  timeHours: (n) => `${n}h ago`,
  timeDays: (n) => `${n}d ago`,
};

/* ---------------------------- choice lists ------------------------------ */

export const CHOICES = {
  appTheme: [
    ['system', 'Follow system'],
    ['dark', 'Dark'],
    ['light', 'Light'],
  ],
  terminalTheme: [
    ['remote', 'Remote Terminal'],
    ['dark', 'Default Dark'],
    ['amoled', 'AMOLED'],
    ['light', 'Light'],
    ['solarized_dark', 'Solarized Dark'],
    ['gruvbox', 'Gruvbox Dark'],
  ],
  cursorStyle: [
    ['block', 'Block'],
    ['underline', 'Underline'],
    ['bar', 'Bar'],
  ],
  bell: [
    ['sound', 'Sound'],
    ['none', 'Silent'],
  ],
  pasteConfirm: [
    [2, '2 lines'],
    [3, '3 lines'],
    [5, '5 lines'],
    [10, '10 lines'],
    [100000, 'Never'],
  ],
  scrollback: [
    [1000, '1 000'],
    [2000, '2 000'],
    [5000, '5 000'],
    [10000, '10 000'],
    [20000, '20 000'],
    [50000, '50 000'],
  ],
  fontSize: [10, 11, 12, 13, 14, 15, 16, 18, 20, 22, 24].map((n) => [n, String(n)]),
  lineSpacing: [
    [0.9, 'Compact'],
    [1.0, 'Normal'],
    [1.15, 'Relaxed'],
    [1.3, 'Loose'],
  ],
  fontFamily: [
    ['bundled', S.fontBundled],
    ['system', S.fontSystem],
  ],
};

export function labelFor(choices, value) {
  const found = choices.find(([v]) => v === value);
  return found ? found[1] : String(value);
}
